# Generated by Django 5.1.4 on 2025-01-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskdetail_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assign_to',
        ),
    ]
