# Generated by Django 5.1.4 on 2025-02-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_taskdetail_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
