# Generated by Django 5.1.4 on 2025-02-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_to',
        ),
    ]
