# Generated by Django 5.1.4 on 2025-02-14 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_assign_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
