# Generated by Django 5.1.4 on 2025-02-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_assign_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
