# Generated by Django 5.1.4 on 2025-02-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/default-image.jpg', null=True, upload_to='task_asset'),
        ),
    ]
